services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.19.4"
      ONLINE_MODE: "false"
      ENABLE_COMMAND_BLOCK: "true"
      TYPE: PAPER
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      VIEW_DISTANCE: 6
      SIMULATION_DISTANCE: 3
    volumes:
      - "./data:/data"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: tcp mc:25565
    ports:
      - "4040:4040"

  notifier:
    build: ./notifier
    depends_on:
      - ngrok
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
